# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.api.inference_api import InferenceApi


class TestInferenceApi(unittest.TestCase):
    """InferenceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InferenceApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_video(self) -> None:
        """Test case for cancel_video

        Cancel a video generation job
        """
        pass

    def test_create_chat_completion(self) -> None:
        """Test case for create_chat_completion

        Create a chat completion (OpenAI-compatible)
        """
        pass

    def test_create_image(self) -> None:
        """Test case for create_image

        Create image (OpenAI-compatible)
        """
        pass

    def test_create_video(self) -> None:
        """Test case for create_video

        Create a video generation job (async)
        """
        pass

    def test_get_model(self) -> None:
        """Test case for get_model

        Get a specific model (OpenAI-compatible)
        """
        pass

    def test_get_video(self) -> None:
        """Test case for get_video

        Get a video generation job
        """
        pass

    def test_get_video_content(self) -> None:
        """Test case for get_video_content

        Download a completed video artifact
        """
        pass

    def test_list_models(self) -> None:
        """Test case for list_models

        List available models (OpenAI-compatible)
        """
        pass

    def test_list_videos(self) -> None:
        """Test case for list_videos

        List video generation jobs
        """
        pass


if __name__ == '__main__':
    unittest.main()
