# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.api.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_create_webhook_endpoint(self) -> None:
        """Test case for create_webhook_endpoint

        Create a webhook endpoint
        """
        pass

    def test_delete_webhook_endpoint(self) -> None:
        """Test case for delete_webhook_endpoint

        Delete a webhook endpoint
        """
        pass

    def test_get_webhook_endpoint(self) -> None:
        """Test case for get_webhook_endpoint

        Get a webhook endpoint
        """
        pass

    def test_list_webhook_endpoints(self) -> None:
        """Test case for list_webhook_endpoints

        List webhook endpoints
        """
        pass


if __name__ == '__main__':
    unittest.main()
