# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.fine_tuning_job import FineTuningJob

class TestFineTuningJob(unittest.TestCase):
    """FineTuningJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FineTuningJob:
        """Test FineTuningJob
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FineTuningJob`
        """
        model = FineTuningJob()
        if include_optional:
            return FineTuningJob(
                id = '',
                object = 'fine_tuning.job',
                model = '',
                created_at = 56,
                finished_at = 56,
                fine_tuned_model = '',
                status = 'validating',
                training_file = '',
                result_files = [
                    ''
                    ],
                error = gpuai_sdk.models.fine_tuning_job_error.FineTuningJob_error(
                    code = '', 
                    message = '', 
                    param = '', ),
                method = gpuai_sdk.models.fine_tuning_job_method.FineTuningJob_method(
                    type = 'lora', 
                    lora = gpuai_sdk.models.create_fine_tuning_job_request_method_lora.CreateFineTuningJobRequest_method_lora(
                        lora_r = 56, 
                        lora_alpha = 56, 
                        lora_dropout = 1.337, ), ),
                seed = 56,
                suffix = '',
                metadata = { }
            )
        else:
            return FineTuningJob(
                id = '',
                object = 'fine_tuning.job',
                model = '',
                created_at = 56,
                status = 'validating',
                training_file = '',
                result_files = [
                    ''
                    ],
        )
        """

    def testFineTuningJob(self):
        """Test FineTuningJob"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
