# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.spending_limit import SpendingLimit

class TestSpendingLimit(unittest.TestCase):
    """SpendingLimit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpendingLimit:
        """Test SpendingLimit
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpendingLimit`
        """
        model = SpendingLimit()
        if include_optional:
            return SpendingLimit(
                monthly_limit_cents = 56,
                monthly_limit_dollars = 1.337,
                current_month_spend_cents = 56,
                current_month_spend_dollars = 1.337,
                percent_used = 1.337,
                billing_cycle_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                enforcement = 'stop_running',
                auto_terminate_hours = 56,
                daily_limit_cents = 56,
                daily_limit_dollars = 1.337,
                current_day_spend_cents = 56
            )
        else:
            return SpendingLimit(
                monthly_limit_cents = 56,
                monthly_limit_dollars = 1.337,
                current_month_spend_cents = 56,
                current_month_spend_dollars = 1.337,
                percent_used = 1.337,
                billing_cycle_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                enforcement = 'stop_running',
                current_day_spend_cents = 56,
        )
        """

    def testSpendingLimit(self):
        """Test SpendingLimit"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
