# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.usage_page import UsagePage

class TestUsagePage(unittest.TestCase):
    """UsagePage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsagePage:
        """Test UsagePage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsagePage`
        """
        model = UsagePage()
        if include_optional:
            return UsagePage(
                data = [
                    gpuai_sdk.models.usage_bucket.UsageBucket(
                        bucket_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        instance_id = '', 
                        gpu_type = '', 
                        gpu_seconds = 56, 
                        cost_cents = 56, )
                    ],
                next_cursor = ''
            )
        else:
            return UsagePage(
                data = [
                    gpuai_sdk.models.usage_bucket.UsageBucket(
                        bucket_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        instance_id = '', 
                        gpu_type = '', 
                        gpu_seconds = 56, 
                        cost_cents = 56, )
                    ],
                next_cursor = '',
        )
        """

    def testUsagePage(self):
        """Test UsagePage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
