# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.template import Template

class TestTemplate(unittest.TestCase):
    """Template unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Template:
        """Test Template
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Template`
        """
        model = Template()
        if include_optional:
            return Template(
                id = '',
                display_name = '',
                category = '',
                kind = 'service',
                status = 'coming_soon',
                container_disk_gb = 56,
                min_vram_gb = 56,
                min_gpu_count = 56,
                ports = [
                    gpuai_sdk.models.template_ports_inner.Template_ports_inner(
                        port = 56, 
                        protocol = 'http', 
                        primary = True, )
                    ],
                env = [
                    gpuai_sdk.models.template_env_inner.Template_env_inner(
                        key = '', 
                        default = '', 
                        user_overridable = True, 
                        secret = True, )
                    ],
                docs_url = '',
                description = '',
                includes = [
                    ''
                    ]
            )
        else:
            return Template(
                id = '',
                display_name = '',
                category = '',
                kind = 'service',
                ports = [
                    gpuai_sdk.models.template_ports_inner.Template_ports_inner(
                        port = 56, 
                        protocol = 'http', 
                        primary = True, )
                    ],
        )
        """

    def testTemplate(self):
        """Test Template"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
