# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.community_machine import CommunityMachine

class TestCommunityMachine(unittest.TestCase):
    """CommunityMachine unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommunityMachine:
        """Test CommunityMachine
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommunityMachine`
        """
        model = CommunityMachine()
        if include_optional:
            return CommunityMachine(
                machine_id = '',
                supplier_id = '',
                gpu_type = '',
                gpu_count = 56,
                vram_per_gpu_gb = 56,
                price_per_hour = 1.337,
                region = '',
                tier = 'on_demand',
                status = 'pending_verification',
                verification_status = 'unverified',
                last_heartbeat_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return CommunityMachine(
                machine_id = '',
                supplier_id = '',
                status = 'pending_verification',
                verification_status = 'unverified',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testCommunityMachine(self):
        """Test CommunityMachine"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
