# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.api.meta_api import MetaApi


class TestMetaApi(unittest.TestCase):
    """MetaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetaApi()

    def tearDown(self) -> None:
        pass

    def test_get_health(self) -> None:
        """Test case for get_health

        Liveness probe
        """
        pass

    def test_get_open_api_spec(self) -> None:
        """Test case for get_open_api_spec

        OpenAPI 3.1 specification
        """
        pass


if __name__ == '__main__':
    unittest.main()
