# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.vm_image import VMImage

class TestVMImage(unittest.TestCase):
    """VMImage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VMImage:
        """Test VMImage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VMImage`
        """
        model = VMImage()
        if include_optional:
            return VMImage(
                label = 'Ubuntu 24.04 LTS',
                family = 'ubuntu',
                version = '24.04',
                driver_preinstalled = True
            )
        else:
            return VMImage(
                label = 'Ubuntu 24.04 LTS',
                family = 'ubuntu',
                version = '24.04',
        )
        """

    def testVMImage(self):
        """Test VMImage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
