# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.webhook_endpoint import WebhookEndpoint

class TestWebhookEndpoint(unittest.TestCase):
    """WebhookEndpoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookEndpoint:
        """Test WebhookEndpoint
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookEndpoint`
        """
        model = WebhookEndpoint()
        if include_optional:
            return WebhookEndpoint(
                id = '',
                url = '',
                secret = '',
                event_types = [
                    'instance.creating'
                    ],
                enabled = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return WebhookEndpoint(
                id = '',
                url = '',
                event_types = [
                    'instance.creating'
                    ],
                enabled = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testWebhookEndpoint(self):
        """Test WebhookEndpoint"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
