# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.chat_completion_request import ChatCompletionRequest

class TestChatCompletionRequest(unittest.TestCase):
    """ChatCompletionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatCompletionRequest:
        """Test ChatCompletionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatCompletionRequest`
        """
        model = ChatCompletionRequest()
        if include_optional:
            return ChatCompletionRequest(
                model = '',
                messages = [
                    gpuai_sdk.models.chat_message.ChatMessage(
                        role = 'system', 
                        content = '', )
                    ],
                temperature = 1.337,
                max_tokens = 1,
                stream = True,
                stream_options = gpuai_sdk.models.stream_options.StreamOptions(
                    include_usage = True, )
            )
        else:
            return ChatCompletionRequest(
                model = '',
                messages = [
                    gpuai_sdk.models.chat_message.ChatMessage(
                        role = 'system', 
                        content = '', )
                    ],
        )
        """

    def testChatCompletionRequest(self):
        """Test ChatCompletionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
