# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.model import Model

class TestModel(unittest.TestCase):
    """Model unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Model:
        """Test Model
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Model`
        """
        model = Model()
        if include_optional:
            return Model(
                id = '',
                object = 'model',
                created = 56,
                owned_by = '',
                author = '',
                modality = 'chat',
                category = '',
                context_length = 56,
                supported_parameters = [
                    ''
                    ],
                parameters = [
                    gpuai_sdk.models.model_parameters_inner.Model_parameters_inner(
                        name = '', 
                        type = 'enum', 
                        enum = [
                            ''
                            ], 
                        min = 56, 
                        max = 56, 
                        default = null, )
                    ],
                pricing = gpuai_sdk.models.model_pricing.Model_pricing(
                    currency = '', 
                    input_per_1m_tokens_cents = 56, 
                    output_per_1m_tokens_cents = 56, 
                    per_image_cents = 56, 
                    per_image_microcents = 56, 
                    per_mpxl_microcents = 56, 
                    per_video_microcents = 56, 
                    per_video_second_cents = 56, 
                    per_video_second_microcents = 56, ),
                aliases = [
                    ''
                    ],
                status = 'active'
            )
        else:
            return Model(
                id = '',
                object = 'model',
                owned_by = '',
                modality = 'chat',
                pricing = gpuai_sdk.models.model_pricing.Model_pricing(
                    currency = '', 
                    input_per_1m_tokens_cents = 56, 
                    output_per_1m_tokens_cents = 56, 
                    per_image_cents = 56, 
                    per_image_microcents = 56, 
                    per_mpxl_microcents = 56, 
                    per_video_microcents = 56, 
                    per_video_second_cents = 56, 
                    per_video_second_microcents = 56, ),
                status = 'active',
        )
        """

    def testModel(self):
        """Test Model"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
