# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.community_earnings import CommunityEarnings

class TestCommunityEarnings(unittest.TestCase):
    """CommunityEarnings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommunityEarnings:
        """Test CommunityEarnings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommunityEarnings`
        """
        model = CommunityEarnings()
        if include_optional:
            return CommunityEarnings(
                accrued_cents = 56,
                unpaid_cents = 56,
                entries = [
                    gpuai_sdk.models.community_earnings_entry.CommunityEarningsEntry(
                        ledger_id = '', 
                        machine_id = '', 
                        instance_id = '', 
                        amount_cents = 56, 
                        accrued_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        paid = True, )
                    ]
            )
        else:
            return CommunityEarnings(
                accrued_cents = 56,
                unpaid_cents = 56,
                entries = [
                    gpuai_sdk.models.community_earnings_entry.CommunityEarningsEntry(
                        ledger_id = '', 
                        machine_id = '', 
                        instance_id = '', 
                        amount_cents = 56, 
                        accrued_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        paid = True, )
                    ],
        )
        """

    def testCommunityEarnings(self):
        """Test CommunityEarnings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
