# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.video_job import VideoJob

class TestVideoJob(unittest.TestCase):
    """VideoJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VideoJob:
        """Test VideoJob
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VideoJob`
        """
        model = VideoJob()
        if include_optional:
            return VideoJob(
                id = '',
                object = 'video',
                model = '',
                status = 'queued',
                progress = 56,
                size = '',
                seconds = 56,
                created_at = 56,
                completed_at = 56,
                expires_at = 56,
                error = '',
                cost_cents = 56
            )
        else:
            return VideoJob(
                id = '',
                object = 'video',
                model = '',
                status = 'queued',
                progress = 56,
                created_at = 56,
        )
        """

    def testVideoJob(self):
        """Test VideoJob"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
