# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.api.fine_tuning_api import FineTuningApi


class TestFineTuningApi(unittest.TestCase):
    """FineTuningApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FineTuningApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_fine_tuning_job(self) -> None:
        """Test case for cancel_fine_tuning_job

        Cancel a fine-tuning job (OpenAI-compatible)
        """
        pass

    def test_create_file(self) -> None:
        """Test case for create_file

        Upload a fine-tuning dataset file (OpenAI-compatible)
        """
        pass

    def test_create_fine_tuning_job(self) -> None:
        """Test case for create_fine_tuning_job

        Create a managed fine-tuning job (OpenAI-compatible)
        """
        pass

    def test_get_fine_tuning_job(self) -> None:
        """Test case for get_fine_tuning_job

        Retrieve a fine-tuning job (OpenAI-compatible)
        """
        pass

    def test_list_fine_tuning_job_events(self) -> None:
        """Test case for list_fine_tuning_job_events

        List fine-tuning job events (OpenAI-compatible)
        """
        pass

    def test_list_fine_tuning_jobs(self) -> None:
        """Test case for list_fine_tuning_jobs

        List fine-tuning jobs (OpenAI-compatible)
        """
        pass


if __name__ == '__main__':
    unittest.main()
