# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.model_pricing import ModelPricing

class TestModelPricing(unittest.TestCase):
    """ModelPricing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelPricing:
        """Test ModelPricing
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelPricing`
        """
        model = ModelPricing()
        if include_optional:
            return ModelPricing(
                currency = '',
                input_per_1m_tokens_cents = 56,
                output_per_1m_tokens_cents = 56,
                per_image_cents = 56,
                per_image_microcents = 56,
                per_mpxl_microcents = 56,
                per_video_microcents = 56,
                per_video_second_cents = 56,
                per_video_second_microcents = 56
            )
        else:
            return ModelPricing(
        )
        """

    def testModelPricing(self):
        """Test ModelPricing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
