# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.gpu_type_page import GPUTypePage

class TestGPUTypePage(unittest.TestCase):
    """GPUTypePage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GPUTypePage:
        """Test GPUTypePage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GPUTypePage`
        """
        model = GPUTypePage()
        if include_optional:
            return GPUTypePage(
                data = [
                    gpuai_sdk.models.gpu_type.GPUType(
                        gpu_type = '', 
                        vram_gb = 56, 
                        cpu_cores = 56, 
                        ram_gb = 56, 
                        storage_gb = 56, 
                        instance_disk_gb = 56, 
                        disk_configurable = True, 
                        architecture = '', )
                    ],
                next_cursor = ''
            )
        else:
            return GPUTypePage(
                data = [
                    gpuai_sdk.models.gpu_type.GPUType(
                        gpu_type = '', 
                        vram_gb = 56, 
                        cpu_cores = 56, 
                        ram_gb = 56, 
                        storage_gb = 56, 
                        instance_disk_gb = 56, 
                        disk_configurable = True, 
                        architecture = '', )
                    ],
                next_cursor = '',
        )
        """

    def testGPUTypePage(self):
        """Test GPUTypePage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
