# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.environments import Environments

class TestEnvironments(unittest.TestCase):
    """Environments unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Environments:
        """Test Environments
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Environments`
        """
        model = Environments()
        if include_optional:
            return Environments(
                frameworks = [pytorch, cuda-devel, jupyter],
                versions = {
                    'key' : [
                        gpuai_sdk.models.framework_version.FrameworkVersion(
                            id = '2.13', 
                            label = 'PyTorch 2.13', 
                            variant = 'cuda124', 
                            default = True, )
                        ]
                    },
                includes = {
                    'key' : {
                        'key' : [
                            gpuai_sdk.models.include_item.IncludeItem(
                                name = 'PyTorch', 
                                version = '2.13.0', )
                            ]
                        }
                    },
                vm_images = {
                    'key' : gpuai_sdk.models.vm_image.VMImage(
                        label = 'Ubuntu 24.04 LTS', 
                        family = 'ubuntu', 
                        version = '24.04', 
                        driver_preinstalled = True, )
                    }
            )
        else:
            return Environments(
                frameworks = [pytorch, cuda-devel, jupyter],
                versions = {
                    'key' : [
                        gpuai_sdk.models.framework_version.FrameworkVersion(
                            id = '2.13', 
                            label = 'PyTorch 2.13', 
                            variant = 'cuda124', 
                            default = True, )
                        ]
                    },
                includes = {
                    'key' : {
                        'key' : [
                            gpuai_sdk.models.include_item.IncludeItem(
                                name = 'PyTorch', 
                                version = '2.13.0', )
                            ]
                        }
                    },
                vm_images = {
                    'key' : gpuai_sdk.models.vm_image.VMImage(
                        label = 'Ubuntu 24.04 LTS', 
                        family = 'ubuntu', 
                        version = '24.04', 
                        driver_preinstalled = True, )
                    },
        )
        """

    def testEnvironments(self):
        """Test Environments"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
