# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.list_deposits200_response import ListDeposits200Response

class TestListDeposits200Response(unittest.TestCase):
    """ListDeposits200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListDeposits200Response:
        """Test ListDeposits200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListDeposits200Response`
        """
        model = ListDeposits200Response()
        if include_optional:
            return ListDeposits200Response(
                deposits = [
                    gpuai_sdk.models.crypto_deposit.CryptoDeposit(
                        deposit_id = '', 
                        status = '', 
                        chain = 'ethereum', 
                        asset = 'usdc', 
                        pay_address = '', 
                        pay_amount = '', 
                        amount_usd_cents = 56, 
                        credited_cents = 56, 
                        tx_hash = '', 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return ListDeposits200Response(
                deposits = [
                    gpuai_sdk.models.crypto_deposit.CryptoDeposit(
                        deposit_id = '', 
                        status = '', 
                        chain = 'ethereum', 
                        asset = 'usdc', 
                        pay_address = '', 
                        pay_amount = '', 
                        amount_usd_cents = 56, 
                        credited_cents = 56, 
                        tx_hash = '', 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testListDeposits200Response(self):
        """Test ListDeposits200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
