# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.list_community_machines200_response import ListCommunityMachines200Response

class TestListCommunityMachines200Response(unittest.TestCase):
    """ListCommunityMachines200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCommunityMachines200Response:
        """Test ListCommunityMachines200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCommunityMachines200Response`
        """
        model = ListCommunityMachines200Response()
        if include_optional:
            return ListCommunityMachines200Response(
                machines = [
                    gpuai_sdk.models.supplier_machine_view.SupplierMachineView(
                        machine_id = '', 
                        gpu_type = '', 
                        gpu_count = 56, 
                        vram_per_gpu_gb = 56, 
                        price_per_hour = 1.337, 
                        region = '', 
                        tier = 'on_demand', 
                        status = 'pending_verification', 
                        verification_status = 'unverified', 
                        online = True, 
                        last_heartbeat_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        first_heartbeat_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        occupied = True, 
                        reliability_score = 1.337, 
                        delist_reason = '', 
                        suspend_reason = '', 
                        agent_version = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return ListCommunityMachines200Response(
                machines = [
                    gpuai_sdk.models.supplier_machine_view.SupplierMachineView(
                        machine_id = '', 
                        gpu_type = '', 
                        gpu_count = 56, 
                        vram_per_gpu_gb = 56, 
                        price_per_hour = 1.337, 
                        region = '', 
                        tier = 'on_demand', 
                        status = 'pending_verification', 
                        verification_status = 'unverified', 
                        online = True, 
                        last_heartbeat_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        first_heartbeat_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        occupied = True, 
                        reliability_score = 1.337, 
                        delist_reason = '', 
                        suspend_reason = '', 
                        agent_version = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testListCommunityMachines200Response(self):
        """Test ListCommunityMachines200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
