# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.pricing_page import PricingPage

class TestPricingPage(unittest.TestCase):
    """PricingPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PricingPage:
        """Test PricingPage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PricingPage`
        """
        model = PricingPage()
        if include_optional:
            return PricingPage(
                data = [
                    gpuai_sdk.models.pricing.Pricing(
                        gpu_type = '', 
                        gpu_count = 56, 
                        cpu_cores = 56, 
                        ram_gb = 56, 
                        storage_gb = 56, 
                        region = '', 
                        tier = 'spot', 
                        price_per_hour = 1.337, 
                        available = 56, 
                        instant_boot = True, 
                        community = True, 
                        instance_disk_gb = 56, 
                        disk_configurable = True, 
                        disk_price_per_gb_hour = 1.337, 
                        capacity_class = 'secure', )
                    ],
                next_cursor = ''
            )
        else:
            return PricingPage(
                data = [
                    gpuai_sdk.models.pricing.Pricing(
                        gpu_type = '', 
                        gpu_count = 56, 
                        cpu_cores = 56, 
                        ram_gb = 56, 
                        storage_gb = 56, 
                        region = '', 
                        tier = 'spot', 
                        price_per_hour = 1.337, 
                        available = 56, 
                        instant_boot = True, 
                        community = True, 
                        instance_disk_gb = 56, 
                        disk_configurable = True, 
                        disk_price_per_gb_hour = 1.337, 
                        capacity_class = 'secure', )
                    ],
                next_cursor = '',
        )
        """

    def testPricingPage(self):
        """Test PricingPage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
