# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.api.community_api import CommunityApi


class TestCommunityApi(unittest.TestCase):
    """CommunityApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CommunityApi()

    def tearDown(self) -> None:
        pass

    def test_delist_community_machine(self) -> None:
        """Test case for delist_community_machine

        Delist a Community Cloud machine
        """
        pass

    def test_enable_community_supplier(self) -> None:
        """Test case for enable_community_supplier

        Enable the Community Cloud supplier role
        """
        pass

    def test_get_community_earnings(self) -> None:
        """Test case for get_community_earnings

        Get your Community Cloud earnings
        """
        pass

    def test_get_community_machine(self) -> None:
        """Test case for get_community_machine

        Get one of your Community Cloud machines
        """
        pass

    def test_get_community_supplier_me(self) -> None:
        """Test case for get_community_supplier_me

        Get the caller's Community Cloud supplier
        """
        pass

    def test_list_community_machines(self) -> None:
        """Test case for list_community_machines

        List your Community Cloud machines
        """
        pass

    def test_reclaim_community_machine(self) -> None:
        """Test case for reclaim_community_machine

        Reclaim a spot-tier Community Cloud machine
        """
        pass

    def test_register_community_machine(self) -> None:
        """Test case for register_community_machine

        Register a Community Cloud machine
        """
        pass

    def test_update_community_machine(self) -> None:
        """Test case for update_community_machine

        Update a Community Cloud machine's price
        """
        pass


if __name__ == '__main__':
    unittest.main()
