# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.instance_page import InstancePage

class TestInstancePage(unittest.TestCase):
    """InstancePage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstancePage:
        """Test InstancePage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstancePage`
        """
        model = InstancePage()
        if include_optional:
            return InstancePage(
                data = [
                    gpuai_sdk.models.instance.Instance(
                        id = '', 
                        name = '', 
                        status = 'allocating', 
                        gpu_type = '', 
                        gpu_count = 1, 
                        region = '', 
                        tier = 'spot', 
                        price_per_hour = 1.337, 
                        connection = gpuai_sdk.models.instance_connection.Instance_connection(
                            hostname = '', 
                            port = 56, 
                            ssh_command = '', 
                            app_url = '', 
                            app_user = '', 
                            app_password = '', 
                            terminal_url = '', ), 
                        disk_gb = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        ready_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        terminated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                next_cursor = ''
            )
        else:
            return InstancePage(
                data = [
                    gpuai_sdk.models.instance.Instance(
                        id = '', 
                        name = '', 
                        status = 'allocating', 
                        gpu_type = '', 
                        gpu_count = 1, 
                        region = '', 
                        tier = 'spot', 
                        price_per_hour = 1.337, 
                        connection = gpuai_sdk.models.instance_connection.Instance_connection(
                            hostname = '', 
                            port = 56, 
                            ssh_command = '', 
                            app_url = '', 
                            app_user = '', 
                            app_password = '', 
                            terminal_url = '', ), 
                        disk_gb = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        ready_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        terminated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                next_cursor = '',
        )
        """

    def testInstancePage(self):
        """Test InstancePage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
