# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.create_fine_tuning_job_request_gpuai import CreateFineTuningJobRequestGpuai

class TestCreateFineTuningJobRequestGpuai(unittest.TestCase):
    """CreateFineTuningJobRequestGpuai unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateFineTuningJobRequestGpuai:
        """Test CreateFineTuningJobRequestGpuai
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateFineTuningJobRequestGpuai`
        """
        model = CreateFineTuningJobRequestGpuai()
        if include_optional:
            return CreateFineTuningJobRequestGpuai(
                max_budget_usd = 1.337,
                gpu_preference = ''
            )
        else:
            return CreateFineTuningJobRequestGpuai(
        )
        """

    def testCreateFineTuningJobRequestGpuai(self):
        """Test CreateFineTuningJobRequestGpuai"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
