# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.api.ssh_keys_api import SshKeysApi


class TestSshKeysApi(unittest.TestCase):
    """SshKeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SshKeysApi()

    def tearDown(self) -> None:
        pass

    def test_create_ssh_key(self) -> None:
        """Test case for create_ssh_key

        Create an SSH key
        """
        pass

    def test_delete_ssh_key(self) -> None:
        """Test case for delete_ssh_key

        Delete an SSH key (idempotent — 404 on already-gone per D-07)
        """
        pass

    def test_get_ssh_key(self) -> None:
        """Test case for get_ssh_key

        Get an SSH key
        """
        pass

    def test_list_ssh_keys(self) -> None:
        """Test case for list_ssh_keys

        List SSH keys
        """
        pass


if __name__ == '__main__':
    unittest.main()
