# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.api.gpu_types_api import GpuTypesApi


class TestGpuTypesApi(unittest.TestCase):
    """GpuTypesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GpuTypesApi()

    def tearDown(self) -> None:
        pass

    def test_list_gpu_types(self) -> None:
        """Test case for list_gpu_types

        List available GPU types (no auth required)
        """
        pass


if __name__ == '__main__':
    unittest.main()
