# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.api.instances_api import InstancesApi


class TestInstancesApi(unittest.TestCase):
    """InstancesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InstancesApi()

    def tearDown(self) -> None:
        pass

    def test_create_instance(self) -> None:
        """Test case for create_instance

        Create an instance (async — returns 202 + Operation-Id header)
        """
        pass

    def test_delete_instance(self) -> None:
        """Test case for delete_instance

        Terminate an instance (idempotent)
        """
        pass

    def test_get_instance(self) -> None:
        """Test case for get_instance

        Get an instance
        """
        pass

    def test_list_instances(self) -> None:
        """Test case for list_instances

        List instances
        """
        pass

    def test_update_instance(self) -> None:
        """Test case for update_instance

        Update an instance (rename only in v1)
        """
        pass


if __name__ == '__main__':
    unittest.main()
