# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.create_fine_tuning_job_request import CreateFineTuningJobRequest

class TestCreateFineTuningJobRequest(unittest.TestCase):
    """CreateFineTuningJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateFineTuningJobRequest:
        """Test CreateFineTuningJobRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateFineTuningJobRequest`
        """
        model = CreateFineTuningJobRequest()
        if include_optional:
            return CreateFineTuningJobRequest(
                model = '',
                training_file = '',
                suffix = '',
                seed = 56,
                method = gpuai_sdk.models.create_fine_tuning_job_request_method.CreateFineTuningJobRequest_method(
                    type = 'lora', 
                    lora = gpuai_sdk.models.create_fine_tuning_job_request_method_lora.CreateFineTuningJobRequest_method_lora(
                        lora_r = 56, 
                        lora_alpha = 56, 
                        lora_dropout = 1.337, ), ),
                gpuai = gpuai_sdk.models.create_fine_tuning_job_request_gpuai.CreateFineTuningJobRequest_gpuai(
                    max_budget_usd = 1.337, 
                    gpu_preference = '', )
            )
        else:
            return CreateFineTuningJobRequest(
                model = '',
                training_file = '',
                method = gpuai_sdk.models.create_fine_tuning_job_request_method.CreateFineTuningJobRequest_method(
                    type = 'lora', 
                    lora = gpuai_sdk.models.create_fine_tuning_job_request_method_lora.CreateFineTuningJobRequest_method_lora(
                        lora_r = 56, 
                        lora_alpha = 56, 
                        lora_dropout = 1.337, ), ),
        )
        """

    def testCreateFineTuningJobRequest(self):
        """Test CreateFineTuningJobRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
