# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.create_instance_request import CreateInstanceRequest

class TestCreateInstanceRequest(unittest.TestCase):
    """CreateInstanceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateInstanceRequest:
        """Test CreateInstanceRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateInstanceRequest`
        """
        model = CreateInstanceRequest()
        if include_optional:
            return CreateInstanceRequest(
                gpu_type = '',
                gpu_count = 1,
                region = '',
                tier = 'spot',
                ssh_key_ids = [
                    ''
                    ],
                name = '',
                max_price_per_hour = 1.337,
                template_id = '',
                environment = 'certified:pytorch@2.13',
                offering_id = '',
                disk_gb = 200,
                env = {
                    'key' : ''
                    }
            )
        else:
            return CreateInstanceRequest(
                gpu_type = '',
                gpu_count = 1,
                tier = 'spot',
        )
        """

    def testCreateInstanceRequest(self):
        """Test CreateInstanceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
