# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.instance_connection import InstanceConnection

class TestInstanceConnection(unittest.TestCase):
    """InstanceConnection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstanceConnection:
        """Test InstanceConnection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstanceConnection`
        """
        model = InstanceConnection()
        if include_optional:
            return InstanceConnection(
                hostname = '',
                port = 56,
                ssh_command = '',
                app_url = '',
                app_user = '',
                app_password = '',
                terminal_url = ''
            )
        else:
            return InstanceConnection(
        )
        """

    def testInstanceConnection(self):
        """Test InstanceConnection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
