# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.fine_tuning_job_event_list import FineTuningJobEventList

class TestFineTuningJobEventList(unittest.TestCase):
    """FineTuningJobEventList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FineTuningJobEventList:
        """Test FineTuningJobEventList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FineTuningJobEventList`
        """
        model = FineTuningJobEventList()
        if include_optional:
            return FineTuningJobEventList(
                object = 'list',
                data = [
                    gpuai_sdk.models.fine_tuning_job_event.FineTuningJobEvent(
                        id = '', 
                        object = 'fine_tuning.job.event', 
                        created_at = 56, 
                        level = 'info', 
                        message = '', 
                        type = '', 
                        data = { }, )
                    ],
                has_more = True
            )
        else:
            return FineTuningJobEventList(
                object = 'list',
                data = [
                    gpuai_sdk.models.fine_tuning_job_event.FineTuningJobEvent(
                        id = '', 
                        object = 'fine_tuning.job.event', 
                        created_at = 56, 
                        level = 'info', 
                        message = '', 
                        type = '', 
                        data = { }, )
                    ],
                has_more = True,
        )
        """

    def testFineTuningJobEventList(self):
        """Test FineTuningJobEventList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
