# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.create_fine_tuning_job_request_method import CreateFineTuningJobRequestMethod

class TestCreateFineTuningJobRequestMethod(unittest.TestCase):
    """CreateFineTuningJobRequestMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateFineTuningJobRequestMethod:
        """Test CreateFineTuningJobRequestMethod
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateFineTuningJobRequestMethod`
        """
        model = CreateFineTuningJobRequestMethod()
        if include_optional:
            return CreateFineTuningJobRequestMethod(
                type = 'lora',
                lora = gpuai_sdk.models.create_fine_tuning_job_request_method_lora.CreateFineTuningJobRequest_method_lora(
                    lora_r = 56, 
                    lora_alpha = 56, 
                    lora_dropout = 1.337, )
            )
        else:
            return CreateFineTuningJobRequestMethod(
                type = 'lora',
        )
        """

    def testCreateFineTuningJobRequestMethod(self):
        """Test CreateFineTuningJobRequestMethod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
