# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gpuai_sdk.models.include_item import IncludeItem

class TestIncludeItem(unittest.TestCase):
    """IncludeItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IncludeItem:
        """Test IncludeItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IncludeItem`
        """
        model = IncludeItem()
        if include_optional:
            return IncludeItem(
                name = 'PyTorch',
                version = '2.13.0'
            )
        else:
            return IncludeItem(
                name = 'PyTorch',
        )
        """

    def testIncludeItem(self):
        """Test IncludeItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
