# coding: utf-8

# flake8: noqa

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.4"

# Define package exports
__all__ = [
    "BillingApi",
    "CommunityApi",
    "EnvironmentsApi",
    "FineTuningApi",
    "GpuTypesApi",
    "InferenceApi",
    "InstancesApi",
    "MetaApi",
    "OperationsApi",
    "PricingApi",
    "SshKeysApi",
    "TemplatesApi",
    "UsageApi",
    "WebhooksApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ChatChoice",
    "ChatCompletionRequest",
    "ChatCompletionResponse",
    "ChatMessage",
    "CommunityEarnings",
    "CommunityEarningsEntry",
    "CommunityMachine",
    "CommunityMachineDelistResult",
    "CommunityMachineRegistration",
    "CommunitySupplier",
    "CreateCryptoDepositRequest",
    "CreateFineTuningJobRequest",
    "CreateFineTuningJobRequestGpuai",
    "CreateFineTuningJobRequestMethod",
    "CreateFineTuningJobRequestMethodLora",
    "CreateInstanceRequest",
    "CreateSshKeyRequest",
    "CreateWebhookEndpointRequest",
    "CryptoDeposit",
    "Environments",
    "FileObject",
    "FineTuningJob",
    "FineTuningJobError",
    "FineTuningJobEvent",
    "FineTuningJobEventList",
    "FineTuningJobList",
    "FineTuningJobMethod",
    "FrameworkVersion",
    "GPUType",
    "GPUTypePage",
    "GetHealth200Response",
    "ImagesGenerationsRequest",
    "ImagesResponse",
    "ImagesResponseDataInner",
    "ImagesResponseUsage",
    "IncludeItem",
    "Instance",
    "InstanceConnection",
    "InstancePage",
    "ListCommunityMachines200Response",
    "ListDeposits200Response",
    "Model",
    "ModelList",
    "ModelParametersInner",
    "ModelPricing",
    "OpenAIErrorEnvelope",
    "OpenAIErrorEnvelopeError",
    "Operation",
    "OperationError",
    "OperationResult",
    "Pricing",
    "PricingPage",
    "Problem",
    "RegisterCommunityMachineRequest",
    "SSHKey",
    "SSHKeyPage",
    "SpendingLimit",
    "StreamOptions",
    "SupplierMachineView",
    "Template",
    "TemplateEnvInner",
    "TemplateList",
    "TemplatePortsInner",
    "UpdateCommunityMachineRequest",
    "UpdateInstanceRequest",
    "UpdateSpendingLimitRequest",
    "Usage",
    "UsageBucket",
    "UsagePage",
    "VMImage",
    "VideoCreateRequest",
    "VideoJob",
    "VideoList",
    "WebhookEndpoint",
    "WebhookEndpointPage",
]

# import apis into sdk package
from gpuai_sdk.api.billing_api import BillingApi as BillingApi
from gpuai_sdk.api.community_api import CommunityApi as CommunityApi
from gpuai_sdk.api.environments_api import EnvironmentsApi as EnvironmentsApi
from gpuai_sdk.api.fine_tuning_api import FineTuningApi as FineTuningApi
from gpuai_sdk.api.gpu_types_api import GpuTypesApi as GpuTypesApi
from gpuai_sdk.api.inference_api import InferenceApi as InferenceApi
from gpuai_sdk.api.instances_api import InstancesApi as InstancesApi
from gpuai_sdk.api.meta_api import MetaApi as MetaApi
from gpuai_sdk.api.operations_api import OperationsApi as OperationsApi
from gpuai_sdk.api.pricing_api import PricingApi as PricingApi
from gpuai_sdk.api.ssh_keys_api import SshKeysApi as SshKeysApi
from gpuai_sdk.api.templates_api import TemplatesApi as TemplatesApi
from gpuai_sdk.api.usage_api import UsageApi as UsageApi
from gpuai_sdk.api.webhooks_api import WebhooksApi as WebhooksApi

# import ApiClient
from gpuai_sdk.api_response import ApiResponse as ApiResponse
from gpuai_sdk.api_client import ApiClient as ApiClient
from gpuai_sdk.configuration import Configuration as Configuration
from gpuai_sdk.exceptions import OpenApiException as OpenApiException
from gpuai_sdk.exceptions import ApiTypeError as ApiTypeError
from gpuai_sdk.exceptions import ApiValueError as ApiValueError
from gpuai_sdk.exceptions import ApiKeyError as ApiKeyError
from gpuai_sdk.exceptions import ApiAttributeError as ApiAttributeError
from gpuai_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from gpuai_sdk.models.chat_choice import ChatChoice as ChatChoice
from gpuai_sdk.models.chat_completion_request import ChatCompletionRequest as ChatCompletionRequest
from gpuai_sdk.models.chat_completion_response import ChatCompletionResponse as ChatCompletionResponse
from gpuai_sdk.models.chat_message import ChatMessage as ChatMessage
from gpuai_sdk.models.community_earnings import CommunityEarnings as CommunityEarnings
from gpuai_sdk.models.community_earnings_entry import CommunityEarningsEntry as CommunityEarningsEntry
from gpuai_sdk.models.community_machine import CommunityMachine as CommunityMachine
from gpuai_sdk.models.community_machine_delist_result import CommunityMachineDelistResult as CommunityMachineDelistResult
from gpuai_sdk.models.community_machine_registration import CommunityMachineRegistration as CommunityMachineRegistration
from gpuai_sdk.models.community_supplier import CommunitySupplier as CommunitySupplier
from gpuai_sdk.models.create_crypto_deposit_request import CreateCryptoDepositRequest as CreateCryptoDepositRequest
from gpuai_sdk.models.create_fine_tuning_job_request import CreateFineTuningJobRequest as CreateFineTuningJobRequest
from gpuai_sdk.models.create_fine_tuning_job_request_gpuai import CreateFineTuningJobRequestGpuai as CreateFineTuningJobRequestGpuai
from gpuai_sdk.models.create_fine_tuning_job_request_method import CreateFineTuningJobRequestMethod as CreateFineTuningJobRequestMethod
from gpuai_sdk.models.create_fine_tuning_job_request_method_lora import CreateFineTuningJobRequestMethodLora as CreateFineTuningJobRequestMethodLora
from gpuai_sdk.models.create_instance_request import CreateInstanceRequest as CreateInstanceRequest
from gpuai_sdk.models.create_ssh_key_request import CreateSshKeyRequest as CreateSshKeyRequest
from gpuai_sdk.models.create_webhook_endpoint_request import CreateWebhookEndpointRequest as CreateWebhookEndpointRequest
from gpuai_sdk.models.crypto_deposit import CryptoDeposit as CryptoDeposit
from gpuai_sdk.models.environments import Environments as Environments
from gpuai_sdk.models.file_object import FileObject as FileObject
from gpuai_sdk.models.fine_tuning_job import FineTuningJob as FineTuningJob
from gpuai_sdk.models.fine_tuning_job_error import FineTuningJobError as FineTuningJobError
from gpuai_sdk.models.fine_tuning_job_event import FineTuningJobEvent as FineTuningJobEvent
from gpuai_sdk.models.fine_tuning_job_event_list import FineTuningJobEventList as FineTuningJobEventList
from gpuai_sdk.models.fine_tuning_job_list import FineTuningJobList as FineTuningJobList
from gpuai_sdk.models.fine_tuning_job_method import FineTuningJobMethod as FineTuningJobMethod
from gpuai_sdk.models.framework_version import FrameworkVersion as FrameworkVersion
from gpuai_sdk.models.gpu_type import GPUType as GPUType
from gpuai_sdk.models.gpu_type_page import GPUTypePage as GPUTypePage
from gpuai_sdk.models.get_health200_response import GetHealth200Response as GetHealth200Response
from gpuai_sdk.models.images_generations_request import ImagesGenerationsRequest as ImagesGenerationsRequest
from gpuai_sdk.models.images_response import ImagesResponse as ImagesResponse
from gpuai_sdk.models.images_response_data_inner import ImagesResponseDataInner as ImagesResponseDataInner
from gpuai_sdk.models.images_response_usage import ImagesResponseUsage as ImagesResponseUsage
from gpuai_sdk.models.include_item import IncludeItem as IncludeItem
from gpuai_sdk.models.instance import Instance as Instance
from gpuai_sdk.models.instance_connection import InstanceConnection as InstanceConnection
from gpuai_sdk.models.instance_page import InstancePage as InstancePage
from gpuai_sdk.models.list_community_machines200_response import ListCommunityMachines200Response as ListCommunityMachines200Response
from gpuai_sdk.models.list_deposits200_response import ListDeposits200Response as ListDeposits200Response
from gpuai_sdk.models.model import Model as Model
from gpuai_sdk.models.model_list import ModelList as ModelList
from gpuai_sdk.models.model_parameters_inner import ModelParametersInner as ModelParametersInner
from gpuai_sdk.models.model_pricing import ModelPricing as ModelPricing
from gpuai_sdk.models.open_ai_error_envelope import OpenAIErrorEnvelope as OpenAIErrorEnvelope
from gpuai_sdk.models.open_ai_error_envelope_error import OpenAIErrorEnvelopeError as OpenAIErrorEnvelopeError
from gpuai_sdk.models.operation import Operation as Operation
from gpuai_sdk.models.operation_error import OperationError as OperationError
from gpuai_sdk.models.operation_result import OperationResult as OperationResult
from gpuai_sdk.models.pricing import Pricing as Pricing
from gpuai_sdk.models.pricing_page import PricingPage as PricingPage
from gpuai_sdk.models.problem import Problem as Problem
from gpuai_sdk.models.register_community_machine_request import RegisterCommunityMachineRequest as RegisterCommunityMachineRequest
from gpuai_sdk.models.ssh_key import SSHKey as SSHKey
from gpuai_sdk.models.ssh_key_page import SSHKeyPage as SSHKeyPage
from gpuai_sdk.models.spending_limit import SpendingLimit as SpendingLimit
from gpuai_sdk.models.stream_options import StreamOptions as StreamOptions
from gpuai_sdk.models.supplier_machine_view import SupplierMachineView as SupplierMachineView
from gpuai_sdk.models.template import Template as Template
from gpuai_sdk.models.template_env_inner import TemplateEnvInner as TemplateEnvInner
from gpuai_sdk.models.template_list import TemplateList as TemplateList
from gpuai_sdk.models.template_ports_inner import TemplatePortsInner as TemplatePortsInner
from gpuai_sdk.models.update_community_machine_request import UpdateCommunityMachineRequest as UpdateCommunityMachineRequest
from gpuai_sdk.models.update_instance_request import UpdateInstanceRequest as UpdateInstanceRequest
from gpuai_sdk.models.update_spending_limit_request import UpdateSpendingLimitRequest as UpdateSpendingLimitRequest
from gpuai_sdk.models.usage import Usage as Usage
from gpuai_sdk.models.usage_bucket import UsageBucket as UsageBucket
from gpuai_sdk.models.usage_page import UsagePage as UsagePage
from gpuai_sdk.models.vm_image import VMImage as VMImage
from gpuai_sdk.models.video_create_request import VideoCreateRequest as VideoCreateRequest
from gpuai_sdk.models.video_job import VideoJob as VideoJob
from gpuai_sdk.models.video_list import VideoList as VideoList
from gpuai_sdk.models.webhook_endpoint import WebhookEndpoint as WebhookEndpoint
from gpuai_sdk.models.webhook_endpoint_page import WebhookEndpointPage as WebhookEndpointPage

