"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from gpuai_sdk.models.pricing_page import PricingPage

from gpuai_sdk.api_client import ApiClient, RequestSerialized
from gpuai_sdk.api_response import ApiResponse
from gpuai_sdk.rest import RESTResponseType


class PricingApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def list_pricing(
        self,
        cursor: Optional[StrictStr] = None,
        limit: Optional[Annotated[int, Field(le=200, strict=True, ge=1)]] = None,
        gpu_type: Annotated[Optional[StrictStr], Field(description="Exact-match filter on gpu_type")] = None,
        region: Annotated[Optional[StrictStr], Field(description="Exact-match filter on canonical region code")] = None,
        tier: Annotated[Optional[StrictStr], Field(description="Exact-match filter on tier")] = None,
        include_unavailable: Annotated[Optional[StrictBool], Field(description="Include offers whose current availability is zero")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> PricingPage:
        """List pricing per GPU type + region (no auth required)

        Lists every distinct offer (gpu_type, gpu_count, region, tier, price, boot class). Customer-identical offers are merged with availability summed. Offers with zero availability are omitted unless include_unavailable=true.

        :param cursor:
        :type cursor: str
        :param limit:
        :type limit: int
        :param gpu_type: Exact-match filter on gpu_type
        :type gpu_type: str
        :param region: Exact-match filter on canonical region code
        :type region: str
        :param tier: Exact-match filter on tier
        :type tier: str
        :param include_unavailable: Include offers whose current availability is zero
        :type include_unavailable: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_pricing_serialize(
            cursor=cursor,
            limit=limit,
            gpu_type=gpu_type,
            region=region,
            tier=tier,
            include_unavailable=include_unavailable,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PricingPage",
            'default': "Problem",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_pricing_with_http_info(
        self,
        cursor: Optional[StrictStr] = None,
        limit: Optional[Annotated[int, Field(le=200, strict=True, ge=1)]] = None,
        gpu_type: Annotated[Optional[StrictStr], Field(description="Exact-match filter on gpu_type")] = None,
        region: Annotated[Optional[StrictStr], Field(description="Exact-match filter on canonical region code")] = None,
        tier: Annotated[Optional[StrictStr], Field(description="Exact-match filter on tier")] = None,
        include_unavailable: Annotated[Optional[StrictBool], Field(description="Include offers whose current availability is zero")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[PricingPage]:
        """List pricing per GPU type + region (no auth required)

        Lists every distinct offer (gpu_type, gpu_count, region, tier, price, boot class). Customer-identical offers are merged with availability summed. Offers with zero availability are omitted unless include_unavailable=true.

        :param cursor:
        :type cursor: str
        :param limit:
        :type limit: int
        :param gpu_type: Exact-match filter on gpu_type
        :type gpu_type: str
        :param region: Exact-match filter on canonical region code
        :type region: str
        :param tier: Exact-match filter on tier
        :type tier: str
        :param include_unavailable: Include offers whose current availability is zero
        :type include_unavailable: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_pricing_serialize(
            cursor=cursor,
            limit=limit,
            gpu_type=gpu_type,
            region=region,
            tier=tier,
            include_unavailable=include_unavailable,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PricingPage",
            'default': "Problem",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_pricing_without_preload_content(
        self,
        cursor: Optional[StrictStr] = None,
        limit: Optional[Annotated[int, Field(le=200, strict=True, ge=1)]] = None,
        gpu_type: Annotated[Optional[StrictStr], Field(description="Exact-match filter on gpu_type")] = None,
        region: Annotated[Optional[StrictStr], Field(description="Exact-match filter on canonical region code")] = None,
        tier: Annotated[Optional[StrictStr], Field(description="Exact-match filter on tier")] = None,
        include_unavailable: Annotated[Optional[StrictBool], Field(description="Include offers whose current availability is zero")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List pricing per GPU type + region (no auth required)

        Lists every distinct offer (gpu_type, gpu_count, region, tier, price, boot class). Customer-identical offers are merged with availability summed. Offers with zero availability are omitted unless include_unavailable=true.

        :param cursor:
        :type cursor: str
        :param limit:
        :type limit: int
        :param gpu_type: Exact-match filter on gpu_type
        :type gpu_type: str
        :param region: Exact-match filter on canonical region code
        :type region: str
        :param tier: Exact-match filter on tier
        :type tier: str
        :param include_unavailable: Include offers whose current availability is zero
        :type include_unavailable: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_pricing_serialize(
            cursor=cursor,
            limit=limit,
            gpu_type=gpu_type,
            region=region,
            tier=tier,
            include_unavailable=include_unavailable,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PricingPage",
            'default': "Problem",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_pricing_serialize(
        self,
        cursor,
        limit,
        gpu_type,
        region,
        tier,
        include_unavailable,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if cursor is not None:
            
            _query_params.append(('cursor', cursor))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if gpu_type is not None:
            
            _query_params.append(('gpu_type', gpu_type))
            
        if region is not None:
            
            _query_params.append(('region', region))
            
        if tier is not None:
            
            _query_params.append(('tier', tier))
            
        if include_unavailable is not None:
            
            _query_params.append(('include_unavailable', include_unavailable))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'application/problem+json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/pricing',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


