# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateInstanceRequest(BaseModel):
    """
    CreateInstanceRequest
    """ # noqa: E501
    gpu_type: StrictStr
    gpu_count: Annotated[int, Field(le=8, strict=True, ge=1)]
    region: Optional[StrictStr] = None
    tier: StrictStr
    ssh_key_ids: Optional[List[StrictStr]] = None
    name: Optional[StrictStr] = None
    max_price_per_hour: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="maximum acceptable whole-instance hourly price (catalog price)")
    template_id: Optional[StrictStr] = Field(default=None, description="Deploy a curated application template (e.g. comfyui, vllm). When set, gpu_type may be omitted — the cheapest eligible GPU is auto-selected. For templates serving a Hugging Face model via env.MODEL (vllm, sglang), the model's published weights size is checked against the GPU's VRAM at submit time: an oversized model on an explicit gpu_type returns 422 `model_too_large` (auto-select instead raises its VRAM floor to the estimate, and 422s only when no available GPU fits). Gated/private/unknown repos are never blocked — the deploy proceeds and the 202 carries a `warnings` entry.")
    environment: Optional[StrictStr] = Field(default=None, description="Launch environment. Omit for the provider default (the GPU.ai Certified Image where supported). Accepted values: `certified` (the GPU.ai Certified base image), `certified:<framework>` (a framework layer — see GET /v1/environments for the roster, e.g. `certified:pytorch`), `certified:<framework>@<version>` (a specific framework version, e.g. `certified:pytorch@2.13`), `raw_vm` (root VM, provider default OS), `raw_vm:<os>` (root VM with a chosen OS, e.g. `raw_vm:ubuntu-24.04`), or `provider_template` (the provider's own image). A well-formed value the placed machine can't serve returns 422 `environment_unavailable`.", json_schema_extra={"examples": ["certified:pytorch@2.13"]})
    offering_id: Optional[StrictStr] = Field(default=None, description="Pin the launch to one exact offering (from GET /v1/pricing) so the engine never substitutes a pricier one. If that offering is gone, the launch fails explicitly rather than silently placing elsewhere.")
    disk_gb: Optional[Annotated[int, Field(strict=True, ge=10)]] = Field(default=None, description="Requested instance filesystem size in GB. Omit for the platform default (100 GB), which never narrows placement. Setting it is a hard requirement: placement narrows to capacity that can honor it (see `disk_configurable` on GET /v1/pricing), and a request no offering of the gpu_type can honor returns 422 `disk_unavailable` rather than launching with a different size. When the launch also pins an exact `offering_id`, a disk_gb larger than that offering's displayed `storage_gb` returns 422 `disk_exceeds_offering` rather than launching with a clamped filesystem. Disk beyond the included allowance (100 GB) is billed at the offering's `disk_price_per_gb_hour` (GET /v1/pricing), folded into the instance's single hourly rate. Bounds: at least 10, at most the platform ceiling (currently 1000) — outside them returns 422 `validation_failed`.", json_schema_extra={"examples": [200]})
    env: Optional[Dict[str, StrictStr]] = Field(default=None, description="Per-deploy env overrides; only keys the template marks user_overridable are accepted (others 422). Secret values are redacted from operation metadata.")
    __properties: ClassVar[List[str]] = ["gpu_type", "gpu_count", "region", "tier", "ssh_key_ids", "name", "max_price_per_hour", "template_id", "environment", "offering_id", "disk_gb", "env"]

    @field_validator('tier')
    def tier_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['spot', 'on_demand']):
            raise ValueError("must be one of enum values ('spot', 'on_demand')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateInstanceRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateInstanceRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "gpu_type": obj.get("gpu_type"),
            "gpu_count": obj.get("gpu_count"),
            "region": obj.get("region"),
            "tier": obj.get("tier"),
            "ssh_key_ids": obj.get("ssh_key_ids"),
            "name": obj.get("name"),
            "max_price_per_hour": obj.get("max_price_per_hour"),
            "template_id": obj.get("template_id"),
            "environment": obj.get("environment"),
            "offering_id": obj.get("offering_id"),
            "disk_gb": obj.get("disk_gb"),
            "env": obj.get("env")
        })
        return _obj


