# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from gpuai_sdk.models.create_fine_tuning_job_request_gpuai import CreateFineTuningJobRequestGpuai
from gpuai_sdk.models.create_fine_tuning_job_request_method import CreateFineTuningJobRequestMethod
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateFineTuningJobRequest(BaseModel):
    """
    Request body for POST /fine_tuning/jobs. The `method` object carries the Axolotl LoRA/QLoRA hyperparameters; `gpuai` is a native extension for the optional budget cap and GPU preference. The backing training environment (image, GPU provider) is an internal orchestration detail and is intentionally absent from this schema (privacy-by-omission, D6).
    """ # noqa: E501
    model: StrictStr = Field(description="An operator-curated tunable base model id.")
    training_file: StrictStr = Field(description="The id of a previously uploaded file (purpose=fine-tune).")
    suffix: Optional[StrictStr] = None
    seed: Optional[StrictInt] = None
    method: CreateFineTuningJobRequestMethod
    gpuai: Optional[CreateFineTuningJobRequestGpuai] = None
    __properties: ClassVar[List[str]] = ["model", "training_file", "suffix", "seed", "method", "gpuai"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateFineTuningJobRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of method
        if self.method:
            _dict['method'] = self.method.to_dict()
        # override the default output from pydantic by calling `to_dict()` of gpuai
        if self.gpuai:
            _dict['gpuai'] = self.gpuai.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateFineTuningJobRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "model": obj.get("model"),
            "training_file": obj.get("training_file"),
            "suffix": obj.get("suffix"),
            "seed": obj.get("seed"),
            "method": CreateFineTuningJobRequestMethod.from_dict(obj["method"]) if obj.get("method") is not None else None,
            "gpuai": CreateFineTuningJobRequestGpuai.from_dict(obj["gpuai"]) if obj.get("gpuai") is not None else None
        })
        return _obj


