# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateCryptoDepositRequest(BaseModel):
    """
    CreateCryptoDepositRequest
    """ # noqa: E501
    amount_cents: StrictInt = Field(description="Amount to deposit in USD cents. Must be at least the configured minimum (500 = $5.00 by default). ")
    chain: StrictStr
    asset: StrictStr
    __properties: ClassVar[List[str]] = ["amount_cents", "chain", "asset"]

    @field_validator('chain')
    def chain_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ethereum', 'base', 'arbitrum', 'polygon', 'solana']):
            raise ValueError("must be one of enum values ('ethereum', 'base', 'arbitrum', 'polygon', 'solana')")
        return value

    @field_validator('asset')
    def asset_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['usdc', 'usdt']):
            raise ValueError("must be one of enum values ('usdc', 'usdt')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateCryptoDepositRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateCryptoDepositRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount_cents": obj.get("amount_cents"),
            "chain": obj.get("chain"),
            "asset": obj.get("asset")
        })
        return _obj


