# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CryptoDeposit(BaseModel):
    """
    A stablecoin deposit. Mirrors the Go DTO field for field. Like that struct, this schema deliberately has NO payment-processor property — the processor is an implementation detail and is structurally absent from the customer contract, not merely filtered out. 
    """ # noqa: E501
    deposit_id: StrictStr
    status: StrictStr = Field(description="Lifecycle state: created, detected, confirming, settled, screening, held_screening, credited, credited_underpaid, credited_overpaid, expired, expired_received, failed, failed_screening. ")
    chain: StrictStr
    asset: StrictStr
    pay_address: Optional[StrictStr] = Field(default=None, description="The address to send funds to. Unique to this deposit.")
    pay_amount: Optional[StrictStr] = Field(default=None, description="The exact token amount to send, as a decimal string (never a number — the value must not round-trip through a float). ")
    amount_usd_cents: StrictInt = Field(description="The amount requested, in USD cents. Never the settled or credited value.")
    credited_cents: Optional[StrictInt] = Field(default=None, description="USD cents actually credited to the balance. Absent until credited.")
    tx_hash: Optional[StrictStr] = None
    expires_at: Optional[datetime] = Field(default=None, description="RFC3339 UTC. After this, send nothing to pay_address.")
    created_at: datetime
    __properties: ClassVar[List[str]] = ["deposit_id", "status", "chain", "asset", "pay_address", "pay_amount", "amount_usd_cents", "credited_cents", "tx_hash", "expires_at", "created_at"]

    @field_validator('chain')
    def chain_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ethereum', 'base', 'arbitrum', 'polygon', 'solana']):
            raise ValueError("must be one of enum values ('ethereum', 'base', 'arbitrum', 'polygon', 'solana')")
        return value

    @field_validator('asset')
    def asset_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['usdc', 'usdt']):
            raise ValueError("must be one of enum values ('usdc', 'usdt')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CryptoDeposit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CryptoDeposit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "deposit_id": obj.get("deposit_id"),
            "status": obj.get("status"),
            "chain": obj.get("chain"),
            "asset": obj.get("asset"),
            "pay_address": obj.get("pay_address"),
            "pay_amount": obj.get("pay_amount"),
            "amount_usd_cents": obj.get("amount_usd_cents"),
            "credited_cents": obj.get("credited_cents"),
            "tx_hash": obj.get("tx_hash"),
            "expires_at": obj.get("expires_at"),
            "created_at": obj.get("created_at")
        })
        return _obj


