# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from gpuai_sdk.models.framework_version import FrameworkVersion
from gpuai_sdk.models.include_item import IncludeItem
from gpuai_sdk.models.vm_image import VMImage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Environments(BaseModel):
    """
    The launch environment catalog (GET /v1/environments).
    """ # noqa: E501
    frameworks: List[StrictStr] = Field(description="Certified framework ids whose images are fully published — the `certified:<framework>` options.", json_schema_extra={"examples": [["pytorch", "cuda-devel", "jupyter"]]})
    versions: Dict[str, List[FrameworkVersion]] = Field(description="The version picker roster: framework id → selectable versions (the `certified:<framework>@<version>` grammar). A framework absent here has one build per CUDA variant. `variant` is the CUDA variant a version targets — only offerings whose GPU maps to it can run it.")
    includes: Dict[str, Dict[str, List[IncludeItem]]] = Field(description="\"What's included\" software lists: framework id (roster ids plus \"base\") → CUDA variant (\"cuda128\"/\"cuda124\") → components.")
    vm_images: Dict[str, VMImage] = Field(description="The raw-VM OS catalog (the `raw_vm:<os>` grammar), keyed by os id.")
    __properties: ClassVar[List[str]] = ["frameworks", "versions", "includes", "vm_images"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Environments from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in versions (dict of array)
        _field_dict_of_array = {}
        if self.versions:
            for _key_versions in self.versions:
                if self.versions[_key_versions] is not None:
                    _field_dict_of_array[_key_versions] = [
                        _item.to_dict() for _item in self.versions[_key_versions]
                    ]
            _dict['versions'] = _field_dict_of_array
        # override the default output from pydantic by calling `to_dict()` of each value in includes (dict of dict)
        _field_dict_of_dict = {}
        if self.includes:
            for _key_includes, _value_includes in self.includes.items():
                if _value_includes is not None:
                    _field_dict_of_dict[_key_includes] = {
                        _key: _value.to_dict() for _key, _value in _value_includes.items()
                    }
            _dict['includes'] = _field_dict_of_dict
        # override the default output from pydantic by calling `to_dict()` of each value in vm_images (dict)
        _field_dict = {}
        if self.vm_images:
            for _key_vm_images in self.vm_images:
                if self.vm_images[_key_vm_images]:
                    _field_dict[_key_vm_images] = self.vm_images[_key_vm_images].to_dict()
            _dict['vm_images'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Environments from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "frameworks": obj.get("frameworks"),
            "versions": {
                _k: [FrameworkVersion.from_dict(_item) for _item in _v] if _v is not None else None
                for _k, _v in obj["versions"].items()
            }
            if obj.get("versions") is not None
            else None,
            "includes": obj.get("includes"),
            "vm_images": dict(
                (_k, VMImage.from_dict(_v))
                for _k, _v in obj["vm_images"].items()
            )
            if obj.get("vm_images") is not None
            else None
        })
        return _obj


