# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from gpuai_sdk.models.fine_tuning_job_error import FineTuningJobError
from gpuai_sdk.models.fine_tuning_job_method import FineTuningJobMethod
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FineTuningJob(BaseModel):
    """
    The fine-tuning job object. `status` is the COLLAPSED public enum (the rich internal states are hidden). `result_files` are freshly-presigned, short-lived download URLs regenerated per read. No backing-provider identity is present (D6).
    """ # noqa: E501
    id: StrictStr
    object: StrictStr
    model: StrictStr
    created_at: StrictInt = Field(description="Unix timestamp (seconds) at creation.")
    finished_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp (seconds) at terminal state; null until terminal.")
    fine_tuned_model: Optional[StrictStr] = Field(default=None, description="Null in this release (catalog auto-serve is a later phase).")
    status: StrictStr
    training_file: StrictStr
    result_files: List[StrictStr]
    error: Optional[FineTuningJobError] = None
    method: Optional[FineTuningJobMethod] = None
    seed: Optional[StrictInt] = None
    suffix: Optional[StrictStr] = None
    metadata: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["id", "object", "model", "created_at", "finished_at", "fine_tuned_model", "status", "training_file", "result_files", "error", "method", "seed", "suffix", "metadata"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['fine_tuning.job']):
            raise ValueError("must be one of enum values ('fine_tuning.job')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['validating', 'queued', 'running', 'succeeded', 'failed', 'cancelled']):
            raise ValueError("must be one of enum values ('validating', 'queued', 'running', 'succeeded', 'failed', 'cancelled')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FineTuningJob from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of error
        if self.error:
            _dict['error'] = self.error.to_dict()
        # override the default output from pydantic by calling `to_dict()` of method
        if self.method:
            _dict['method'] = self.method.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FineTuningJob from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "object": obj.get("object"),
            "model": obj.get("model"),
            "created_at": obj.get("created_at"),
            "finished_at": obj.get("finished_at"),
            "fine_tuned_model": obj.get("fine_tuned_model"),
            "status": obj.get("status"),
            "training_file": obj.get("training_file"),
            "result_files": obj.get("result_files"),
            "error": FineTuningJobError.from_dict(obj["error"]) if obj.get("error") is not None else None,
            "method": FineTuningJobMethod.from_dict(obj["method"]) if obj.get("method") is not None else None,
            "seed": obj.get("seed"),
            "suffix": obj.get("suffix"),
            "metadata": obj.get("metadata")
        })
        return _obj


