# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GPUType(BaseModel):
    """
    GPUType
    """ # noqa: E501
    gpu_type: StrictStr
    vram_gb: StrictInt
    cpu_cores: Optional[StrictInt] = Field(default=None, description="Representative host vCPU count for this GPU model. Unlike vram_gb (invariant per model) this varies per offering, so it is the first-sighting/typical value; GET /v1/pricing carries the exact per-offering spec. 0 marks a spec the upstream did not report.")
    ram_gb: Optional[StrictInt] = Field(default=None, description="Representative host RAM (GB) for this GPU model; varies per offering — see cpu_cores. 0 marks an unreported spec.")
    storage_gb: Optional[StrictInt] = Field(default=None, description="Representative host storage (GB) for this GPU model; varies per offering — see cpu_cores. 0 marks an unreported spec.")
    instance_disk_gb: Optional[StrictInt] = Field(default=None, description="Representative instance filesystem size (GB) a launch of this model receives — the platform default where the upstream honors a configured size, otherwise the machine's reported disk; varies per offering — see cpu_cores. 0 marks an unreported disk (unknown, not zero). GET /v1/pricing carries the exact per-offering value.")
    disk_configurable: Optional[StrictBool] = Field(default=None, description="true when at least one offering of this model accepts a custom disk_gb at launch (an OR across offerings — requesting disk_gb narrows placement to the capable capacity).")
    architecture: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["gpu_type", "vram_gb", "cpu_cores", "ram_gb", "storage_gb", "instance_disk_gb", "disk_configurable", "architecture"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GPUType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GPUType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "gpu_type": obj.get("gpu_type"),
            "vram_gb": obj.get("vram_gb"),
            "cpu_cores": obj.get("cpu_cores"),
            "ram_gb": obj.get("ram_gb"),
            "storage_gb": obj.get("storage_gb"),
            "instance_disk_gb": obj.get("instance_disk_gb"),
            "disk_configurable": obj.get("disk_configurable"),
            "architecture": obj.get("architecture")
        })
        return _obj


