# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ImagesGenerationsRequest(BaseModel):
    """
    ImagesGenerationsRequest
    """ # noqa: E501
    model: StrictStr = Field(description="Customer-facing image model id (e.g. gpuai/flux.1-schnell) or alias.")
    prompt: StrictStr = Field(description="Text description of the image(s) to generate.")
    n: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=1, description="Number of images to generate. Defaults to 1.")
    size: Optional[StrictStr] = Field(default=None, description="Output image dimensions as WxH (e.g. 1024x1024).")
    response_format: Optional[StrictStr] = Field(default='b64_json', description="Only b64_json is supported. A value of \"url\" is rejected with invalid_request_error until S3-backed URL delivery lands.")
    __properties: ClassVar[List[str]] = ["model", "prompt", "n", "size", "response_format"]

    @field_validator('response_format')
    def response_format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['b64_json']):
            raise ValueError("must be one of enum values ('b64_json')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ImagesGenerationsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ImagesGenerationsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "model": obj.get("model"),
            "prompt": obj.get("prompt"),
            "n": obj.get("n") if obj.get("n") is not None else 1,
            "size": obj.get("size"),
            "response_format": obj.get("response_format") if obj.get("response_format") is not None else 'b64_json'
        })
        return _obj


