# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from gpuai_sdk.models.instance_connection import InstanceConnection
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Instance(BaseModel):
    """
    Instance
    """ # noqa: E501
    id: StrictStr
    name: Optional[StrictStr] = None
    status: StrictStr = Field(description="Customer-facing lifecycle status. \"allocating\" = the GPU is still being acquired from the provider (slow-boot capacity such as baremetal can take ~15 min); \"starting\" = the node exists and is booting; \"running\" = ready to use.")
    gpu_type: StrictStr
    gpu_count: Annotated[int, Field(le=8, strict=True, ge=1)]
    region: StrictStr
    tier: StrictStr
    price_per_hour: Union[StrictFloat, StrictInt] = Field(description="hourly rate for the whole instance — covers all gpu_count GPUs")
    connection: Optional[InstanceConnection] = None
    disk_gb: Optional[StrictInt] = Field(default=None, description="Instance filesystem size in GB that the platform configured for this launch. Present only where the placed capacity honors a configured disk size; absent means the machine's disk is provider-determined (its own flavor volume).")
    status_reason: Optional[StrictStr] = Field(default=None, description="Why the instance is in the error state, e.g. \"provisioning stalled: the instance started but never became reachable\". Present only on errored instances.")
    created_at: datetime
    ready_at: Optional[datetime] = None
    terminated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "name", "status", "gpu_type", "gpu_count", "region", "tier", "price_per_hour", "connection", "disk_gb", "status_reason", "created_at", "ready_at", "terminated_at"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['allocating', 'starting', 'running', 'stopping', 'stopped', 'terminated', 'error']):
            raise ValueError("must be one of enum values ('allocating', 'starting', 'running', 'stopping', 'stopped', 'terminated', 'error')")
        return value

    @field_validator('tier')
    def tier_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['spot', 'on_demand']):
            raise ValueError("must be one of enum values ('spot', 'on_demand')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Instance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of connection
        if self.connection:
            _dict['connection'] = self.connection.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Instance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "status": obj.get("status"),
            "gpu_type": obj.get("gpu_type"),
            "gpu_count": obj.get("gpu_count"),
            "region": obj.get("region"),
            "tier": obj.get("tier"),
            "price_per_hour": obj.get("price_per_hour"),
            "connection": InstanceConnection.from_dict(obj["connection"]) if obj.get("connection") is not None else None,
            "disk_gb": obj.get("disk_gb"),
            "status_reason": obj.get("status_reason"),
            "created_at": obj.get("created_at"),
            "ready_at": obj.get("ready_at"),
            "terminated_at": obj.get("terminated_at")
        })
        return _obj


