# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from gpuai_sdk.models.model_parameters_inner import ModelParametersInner
from gpuai_sdk.models.model_pricing import ModelPricing
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Model(BaseModel):
    """
    Model
    """ # noqa: E501
    id: StrictStr
    object: StrictStr
    created: Optional[StrictInt] = None
    owned_by: StrictStr
    author: Optional[StrictStr] = Field(default=None, description="Model creator/organization (e.g. \"Meta\", \"Qwen\", \"Black Forest Labs\").")
    modality: StrictStr
    category: Optional[StrictStr] = Field(default=None, description="Browse-facing category; mirrors modality (chat/image/video).")
    context_length: Optional[StrictInt] = None
    supported_parameters: Optional[List[StrictStr]] = None
    parameters: Optional[List[ModelParametersInner]] = Field(default=None, description="Typed parameter descriptors for media (image/video) models — name, type, enum/bounds/default. Playgrounds render input forms from these.")
    pricing: ModelPricing
    aliases: Optional[List[StrictStr]] = None
    status: StrictStr
    __properties: ClassVar[List[str]] = ["id", "object", "created", "owned_by", "author", "modality", "category", "context_length", "supported_parameters", "parameters", "pricing", "aliases", "status"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['model']):
            raise ValueError("must be one of enum values ('model')")
        return value

    @field_validator('modality')
    def modality_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['chat', 'image', 'video']):
            raise ValueError("must be one of enum values ('chat', 'image', 'video')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['active', 'coming_soon', 'deprecated']):
            raise ValueError("must be one of enum values ('active', 'coming_soon', 'deprecated')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Model from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in parameters (list)
        _items = []
        if self.parameters:
            for _item_parameters in self.parameters:
                if _item_parameters:
                    _items.append(_item_parameters.to_dict())
            _dict['parameters'] = _items
        # override the default output from pydantic by calling `to_dict()` of pricing
        if self.pricing:
            _dict['pricing'] = self.pricing.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Model from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "object": obj.get("object"),
            "created": obj.get("created"),
            "owned_by": obj.get("owned_by"),
            "author": obj.get("author"),
            "modality": obj.get("modality"),
            "category": obj.get("category"),
            "context_length": obj.get("context_length"),
            "supported_parameters": obj.get("supported_parameters"),
            "parameters": [ModelParametersInner.from_dict(_item) for _item in obj["parameters"]] if obj.get("parameters") is not None else None,
            "pricing": ModelPricing.from_dict(obj["pricing"]) if obj.get("pricing") is not None else None,
            "aliases": obj.get("aliases"),
            "status": obj.get("status")
        })
        return _obj


