# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ModelPricing(BaseModel):
    """
    ModelPricing
    """ # noqa: E501
    currency: Optional[StrictStr] = None
    input_per_1m_tokens_cents: Optional[StrictInt] = None
    output_per_1m_tokens_cents: Optional[StrictInt] = None
    per_image_cents: Optional[StrictInt] = None
    per_image_microcents: Optional[StrictInt] = Field(default=None, description="Exact per-image rate in micro-cents (1e-6 cent). Prefer this for image models — per_image_cents rounds sub-cent prices to 0.")
    per_mpxl_microcents: Optional[StrictInt] = Field(default=None, description="Price per output megapixel in micro-cents (1e-6 cent) for image models metered per megapixel. Mutually exclusive with the per-image fields.")
    per_video_microcents: Optional[StrictInt] = Field(default=None, description="Representative per-clip price in micro-cents (1e-6 cent) for video models — a \"from\" price taken from the provider's published example rate.")
    per_video_second_cents: Optional[StrictInt] = None
    per_video_second_microcents: Optional[StrictInt] = Field(default=None, description="Exact per-second-of-output-video rate in micro-cents (1e-6 cent). Prefer this for video models.")
    __properties: ClassVar[List[str]] = ["currency", "input_per_1m_tokens_cents", "output_per_1m_tokens_cents", "per_image_cents", "per_image_microcents", "per_mpxl_microcents", "per_video_microcents", "per_video_second_cents", "per_video_second_microcents"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelPricing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelPricing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "currency": obj.get("currency"),
            "input_per_1m_tokens_cents": obj.get("input_per_1m_tokens_cents"),
            "output_per_1m_tokens_cents": obj.get("output_per_1m_tokens_cents"),
            "per_image_cents": obj.get("per_image_cents"),
            "per_image_microcents": obj.get("per_image_microcents"),
            "per_mpxl_microcents": obj.get("per_mpxl_microcents"),
            "per_video_microcents": obj.get("per_video_microcents"),
            "per_video_second_cents": obj.get("per_video_second_cents"),
            "per_video_second_microcents": obj.get("per_video_second_microcents")
        })
        return _obj


