# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from gpuai_sdk.models.operation_error import OperationError
from gpuai_sdk.models.operation_result import OperationResult
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Operation(BaseModel):
    """
    Operation
    """ # noqa: E501
    operation_id: UUID
    kind: StrictStr
    state: StrictStr
    resource_id: Optional[StrictStr] = None
    error: Optional[OperationError] = None
    result: Optional[OperationResult] = None
    created_at: datetime
    updated_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    warnings: Optional[List[StrictStr]] = Field(default=None, description="Create-time advisories, present only on the synchronous 202 from POST /instances (never on GET /operations/{id} polls) — e.g. the model-size guard failing open because a template deploy's MODEL is a gated or unknown Hugging Face repo whose size could not be verified.")
    __properties: ClassVar[List[str]] = ["operation_id", "kind", "state", "resource_id", "error", "result", "created_at", "updated_at", "completed_at", "warnings"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['instance.create', 'instance.delete']):
            raise ValueError("must be one of enum values ('instance.create', 'instance.delete')")
        return value

    @field_validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending', 'in_progress', 'succeeded', 'failed', 'cancelled']):
            raise ValueError("must be one of enum values ('pending', 'in_progress', 'succeeded', 'failed', 'cancelled')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Operation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of error
        if self.error:
            _dict['error'] = self.error.to_dict()
        # override the default output from pydantic by calling `to_dict()` of result
        if self.result:
            _dict['result'] = self.result.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Operation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "operation_id": obj.get("operation_id"),
            "kind": obj.get("kind"),
            "state": obj.get("state"),
            "resource_id": obj.get("resource_id"),
            "error": OperationError.from_dict(obj["error"]) if obj.get("error") is not None else None,
            "result": OperationResult.from_dict(obj["result"]) if obj.get("result") is not None else None,
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "completed_at": obj.get("completed_at"),
            "warnings": obj.get("warnings")
        })
        return _obj


