# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Pricing(BaseModel):
    """
    Pricing
    """ # noqa: E501
    gpu_type: StrictStr
    gpu_count: StrictInt = Field(description="number of GPUs in the listed configuration")
    cpu_cores: Optional[StrictInt] = Field(default=None, description="host vCPU count for this offering, tied to the shown (cheapest) price. 0 marks an unreported spec.")
    ram_gb: Optional[StrictInt] = Field(default=None, description="host RAM (GB) for this offering, tied to the shown price. 0 marks an unreported spec.")
    storage_gb: Optional[StrictInt] = Field(default=None, description="host storage (GB) for this offering, tied to the shown price. 0 marks an unreported spec.")
    region: StrictStr
    tier: StrictStr
    price_per_hour: Union[StrictFloat, StrictInt] = Field(description="hourly price for the whole listed configuration — covers all gpu_count GPUs")
    available: StrictInt = Field(description="count of available units, summed across merged identical offers")
    instant_boot: StrictBool = Field(description="true when instances of this offering are typically reachable within about a minute of launch; false for capacity with longer provisioning times (~3-5 minutes)")
    community: StrictBool = Field(description="true when this offering is community-supplied capacity")
    instance_disk_gb: Optional[StrictInt] = Field(default=None, description="Instance filesystem size (GB) a launch of THIS offering receives — the platform default where the upstream honors a configured size, otherwise the machine's own reported disk; tied to the shown (cheapest) price like cpu_cores. 0 marks an unreported disk (unknown, not zero).")
    disk_configurable: Optional[StrictBool] = Field(default=None, description="true when a launch of this offering may choose its own disk size via the create request's disk_gb. A distinguishing field in the offer merge — configurable and fixed-disk capacity for the same SKU stay separate rows.")
    disk_price_per_gb_hour: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Retail price of one GB of instance disk beyond instance_disk_gb, per hour, for launches of this offering. A launch requesting disk_gb above instance_disk_gb is billed approximately price_per_hour + (disk_gb − instance_disk_gb) × disk_price_per_gb_hour (the exact billed rate folds disk into one cent-rounded hourly price). 0 when the offering is not disk-configurable, or when disk above the included allowance is currently free.")
    capacity_class: Optional[StrictStr] = Field(default=None, description="per-offering capacity classification — \"secure\" for datacenter-operated hardware, \"community\" for supplier/peer-hosted hardware with a softer SLA. The string twin of `community`, classified per offering rather than per upstream. May transiently be empty for cache entries written before the field existed.")
    __properties: ClassVar[List[str]] = ["gpu_type", "gpu_count", "cpu_cores", "ram_gb", "storage_gb", "region", "tier", "price_per_hour", "available", "instant_boot", "community", "instance_disk_gb", "disk_configurable", "disk_price_per_gb_hour", "capacity_class"]

    @field_validator('tier')
    def tier_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['spot', 'on_demand']):
            raise ValueError("must be one of enum values ('spot', 'on_demand')")
        return value

    @field_validator('capacity_class')
    def capacity_class_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['secure', 'community', '']):
            raise ValueError("must be one of enum values ('secure', 'community', '')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Pricing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Pricing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "gpu_type": obj.get("gpu_type"),
            "gpu_count": obj.get("gpu_count"),
            "cpu_cores": obj.get("cpu_cores"),
            "ram_gb": obj.get("ram_gb"),
            "storage_gb": obj.get("storage_gb"),
            "region": obj.get("region"),
            "tier": obj.get("tier"),
            "price_per_hour": obj.get("price_per_hour"),
            "available": obj.get("available"),
            "instant_boot": obj.get("instant_boot"),
            "community": obj.get("community"),
            "instance_disk_gb": obj.get("instance_disk_gb"),
            "disk_configurable": obj.get("disk_configurable"),
            "disk_price_per_gb_hour": obj.get("disk_price_per_gb_hour"),
            "capacity_class": obj.get("capacity_class")
        })
        return _obj


