# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Problem(BaseModel):
    """
    Problem
    """ # noqa: E501
    type: StrictStr
    title: StrictStr
    status: StrictInt
    detail: StrictStr
    code: StrictStr
    request_id: StrictStr
    __properties: ClassVar[List[str]] = ["type", "title", "status", "detail", "code", "request_id"]

    @field_validator('code')
    def code_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['unauthenticated', 'invalid_api_key', 'insufficient_scope', 'not_found', 'idempotency_conflict', 'idempotency_mismatch', 'validation_failed', 'invalid_gpu_type', 'disk_unavailable', 'disk_exceeds_offering', 'model_too_large', 'insufficient_balance', 'quota_exceeded', 'rate_limited', 'internal_error', 'operation_failed']):
            raise ValueError("must be one of enum values ('unauthenticated', 'invalid_api_key', 'insufficient_scope', 'not_found', 'idempotency_conflict', 'idempotency_mismatch', 'validation_failed', 'invalid_gpu_type', 'disk_unavailable', 'disk_exceeds_offering', 'model_too_large', 'insufficient_balance', 'quota_exceeded', 'rate_limited', 'internal_error', 'operation_failed')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Problem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Problem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "title": obj.get("title"),
            "status": obj.get("status"),
            "detail": obj.get("detail"),
            "code": obj.get("code"),
            "request_id": obj.get("request_id")
        })
        return _obj


