# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RegisterCommunityMachineRequest(BaseModel):
    """
    All fields optional; an empty body registers a zero-spec placeholder in pending_verification.
    """ # noqa: E501
    gpu_type: Optional[Annotated[str, Field(strict=True, max_length=50)]] = None
    gpu_count: Optional[Annotated[int, Field(le=64, strict=True, ge=1)]] = None
    vram_per_gpu_gb: Optional[Annotated[int, Field(le=2048, strict=True, ge=1)]] = None
    price_per_hour: Optional[Union[Annotated[float, Field(le=10000, strict=True, ge=0)], Annotated[int, Field(le=10000, strict=True, ge=0)]]] = None
    region: Optional[Annotated[str, Field(strict=True, max_length=50)]] = None
    tier: Optional[StrictStr] = Field(default=None, description="Supplier-chosen rental model. Optional; omitted resolves to on_demand. spot lists the machine as cheaper interruptible capacity.")
    __properties: ClassVar[List[str]] = ["gpu_type", "gpu_count", "vram_per_gpu_gb", "price_per_hour", "region", "tier"]

    @field_validator('tier')
    def tier_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['on_demand', 'spot']):
            raise ValueError("must be one of enum values ('on_demand', 'spot')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RegisterCommunityMachineRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RegisterCommunityMachineRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "gpu_type": obj.get("gpu_type"),
            "gpu_count": obj.get("gpu_count"),
            "vram_per_gpu_gb": obj.get("vram_per_gpu_gb"),
            "price_per_hour": obj.get("price_per_hour"),
            "region": obj.get("region"),
            "tier": obj.get("tier")
        })
        return _obj


