# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SupplierMachineView(BaseModel):
    """
    The supplier-facing projection of a community machine. `occupied` replaces the renting customer's instance id (never exposed to the supplier); `online` is the server-derived 60s-heartbeat liveness.
    """ # noqa: E501
    machine_id: UUID
    gpu_type: Optional[StrictStr] = None
    gpu_count: Optional[StrictInt] = None
    vram_per_gpu_gb: Optional[StrictInt] = None
    price_per_hour: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Whole-machine hourly rate (never per-GPU).")
    region: Optional[StrictStr] = None
    tier: StrictStr
    status: StrictStr
    verification_status: StrictStr
    online: StrictBool = Field(description="Server-derived — heartbeated within the last 60 seconds.")
    last_heartbeat_at: Optional[datetime] = None
    first_heartbeat_at: Optional[datetime] = None
    occupied: StrictBool = Field(description="A customer instance is currently renting this machine.")
    reliability_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Server-computed 0–100; machines below the platform threshold are auto-delisted.")
    delist_reason: Optional[StrictStr] = None
    suspend_reason: Optional[StrictStr] = None
    agent_version: Optional[StrictStr] = None
    created_at: datetime
    __properties: ClassVar[List[str]] = ["machine_id", "gpu_type", "gpu_count", "vram_per_gpu_gb", "price_per_hour", "region", "tier", "status", "verification_status", "online", "last_heartbeat_at", "first_heartbeat_at", "occupied", "reliability_score", "delist_reason", "suspend_reason", "agent_version", "created_at"]

    @field_validator('tier')
    def tier_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['on_demand', 'spot']):
            raise ValueError("must be one of enum values ('on_demand', 'spot')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending_verification', 'listed', 'delisted', 'suspended', 'draining']):
            raise ValueError("must be one of enum values ('pending_verification', 'listed', 'delisted', 'suspended', 'draining')")
        return value

    @field_validator('verification_status')
    def verification_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['unverified', 'verified', 'failed']):
            raise ValueError("must be one of enum values ('unverified', 'verified', 'failed')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SupplierMachineView from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SupplierMachineView from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "machine_id": obj.get("machine_id"),
            "gpu_type": obj.get("gpu_type"),
            "gpu_count": obj.get("gpu_count"),
            "vram_per_gpu_gb": obj.get("vram_per_gpu_gb"),
            "price_per_hour": obj.get("price_per_hour"),
            "region": obj.get("region"),
            "tier": obj.get("tier"),
            "status": obj.get("status"),
            "verification_status": obj.get("verification_status"),
            "online": obj.get("online"),
            "last_heartbeat_at": obj.get("last_heartbeat_at"),
            "first_heartbeat_at": obj.get("first_heartbeat_at"),
            "occupied": obj.get("occupied"),
            "reliability_score": obj.get("reliability_score"),
            "delist_reason": obj.get("delist_reason"),
            "suspend_reason": obj.get("suspend_reason"),
            "agent_version": obj.get("agent_version"),
            "created_at": obj.get("created_at")
        })
        return _obj


