# coding: utf-8

"""
    GPU.ai Public Developer API

    Programmatic API for GPU.ai. Authenticate with API keys minted from the dashboard. See https://gpu.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@gpu.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from gpuai_sdk.models.template_env_inner import TemplateEnvInner
from gpuai_sdk.models.template_ports_inner import TemplatePortsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Template(BaseModel):
    """
    A deployable application template. The container image (registry path) and start command are internal orchestration details and are intentionally absent from this schema (TMPL-13 defense-by-omission).
    """ # noqa: E501
    id: StrictStr
    display_name: StrictStr
    category: StrictStr
    kind: StrictStr = Field(description="Deployable kind. \"service\" is a long-running app exposed at connection.app_url. \"finetuning\" is a run-to-completion job (no app_url) and is currently advertised only as a coming-soon catalog entry — not yet deployable.")
    status: Optional[StrictStr] = None
    container_disk_gb: Optional[StrictInt] = None
    min_vram_gb: Optional[StrictInt] = None
    min_gpu_count: Optional[StrictInt] = None
    ports: List[TemplatePortsInner]
    env: Optional[List[TemplateEnvInner]] = None
    docs_url: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    includes: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["id", "display_name", "category", "kind", "status", "container_disk_gb", "min_vram_gb", "min_gpu_count", "ports", "env", "docs_url", "description", "includes"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['service', 'finetuning']):
            raise ValueError("must be one of enum values ('service', 'finetuning')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['coming_soon']):
            raise ValueError("must be one of enum values ('coming_soon')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Template from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in ports (list)
        _items = []
        if self.ports:
            for _item_ports in self.ports:
                if _item_ports:
                    _items.append(_item_ports.to_dict())
            _dict['ports'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in env (list)
        _items = []
        if self.env:
            for _item_env in self.env:
                if _item_env:
                    _items.append(_item_env.to_dict())
            _dict['env'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Template from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "display_name": obj.get("display_name"),
            "category": obj.get("category"),
            "kind": obj.get("kind"),
            "status": obj.get("status"),
            "container_disk_gb": obj.get("container_disk_gb"),
            "min_vram_gb": obj.get("min_vram_gb"),
            "min_gpu_count": obj.get("min_gpu_count"),
            "ports": [TemplatePortsInner.from_dict(_item) for _item in obj["ports"]] if obj.get("ports") is not None else None,
            "env": [TemplateEnvInner.from_dict(_item) for _item in obj["env"]] if obj.get("env") is not None else None,
            "docs_url": obj.get("docs_url"),
            "description": obj.get("description"),
            "includes": obj.get("includes")
        })
        return _obj


